### PR TITLE
allows users to sign out

### PR DESCRIPTION
**Pull request by hernanat**
Not sure why we didn't have this before ... oops.

### CODE REVIEW

**Comment by hernanat** [comment]
I put it in the footer ... didn't feel like doing another dropdown...we could always move if we want though?

**Comment by hernanat** [comment]
[Allow users to sign out](https://trello.com/c/AlyrYk0j/53-allow-users-to-sign-out)

**Comment by ashpil** [comment]
It would also actually be good if we got in #68 before this, so we can add this to the row in the footer where logged in user stuff happens

**Comment by ashpil** [comment]
This one good after squash as well I think.

**Review by ashpil — DISMISSED** [review]

**Review by ashpil — APPROVED** [review]

**Comment by hernanat** [comment]
thanks @ashpil

**Pull request merged**
